# Generated by Django 2.2.5 on 2019-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0003_auto_20190912_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='d/m/y'),
        ),
    ]
